task:
  name: Build Android example app
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd flutter_local_notifications/example
    - flutter build apk --debug

task:
  name: Build iOS example app
  osx_instance:
    image: catalina-flutter
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd flutter_local_notifications/example
    - flutter build ios --no-codesign --debug

task:
  name: Run platform interface tests
  container:
    image: cirrusci/flutter:stable
  test_script:
    - cd flutter_local_notifications_platform_interface
    - flutter test

task:
  name: Run plugin unit tests
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - cd flutter_local_notifications
    - flutter test