task:
  name: Build Android example app
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd flutter_local_notifications/example
    - flutter build apk --debug

task:
  name: Build iOS example app
  osx_instance:
    image: big-sur-xcode-12.4
  pub_cache:
    folder: ~/.pub-cache
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  build_script:
    - cd flutter_local_notifications/example
    - flutter build ios --no-codesign --debug

task:
  name: Build macOS example app
  osx_instance:
    image: big-sur-xcode-12.4
  pub_cache:
    folder: ~/.pub-cache
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  setup_script:
    - flutter config --enable-macos-desktop
  build_script:
    - cd flutter_local_notifications/example
    - flutter build macos

task:
  name: Build Linux example app
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  setup_script:
    - apt update
    - apt install cmake ninja-build clang pkg-config libgtk-3-dev -y
    - flutter config --enable-linux-desktop
  build_script:
    - cd flutter_local_notifications/example
    - flutter build linux

task:
  name: Run platform interface tests
  container:
    image: cirrusci/flutter:stable
  test_script:
    - cd flutter_local_notifications_platform_interface
    - flutter test

task:
  name: Run plugin unit tests
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - cd flutter_local_notifications
    - flutter test

task:
  name: Run integration tests (Android)
  env:
    EMULATOR_API_LEVEL: 28
    ANDROID_ABI: "default;x86"
  container:
    image: cirrusci/flutter:stable
    cpu: 4
    memory: 10G
    kvm: true
  pub_cache:
    folder: ~/.pub-cache
  install_images_script: sdkmanager "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  create_device_script:
    echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator -no-window -verbose -avd test -no-audio -no-window
  wait_for_emulator_script:
    android-wait-for-emulator
  test_script:
    - cd flutter_local_notifications
    - cd example
    - flutter drive --driver=test_driver/integration_test.dart --target=integration_test/flutter_local_notifications_test.dart

task:
  name: Run Linux plugin tests
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - cd flutter_local_notifications_linux
    - flutter test
