build_example_android_task:
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd flutter_local_notifications/example
    - flutter build apk --debug

build_example_ios_task:
  osx_instance:
    image: catalina-flutter
  pub_cache:
    folder: ~/.pub-cache
  build_script:
    - cd flutter_local_notifications/example
    - flutter build ios --no-codesign --debug

test_platform_interface_task:
  container:
    image: cirrusci/flutter:stable
  test_script:
    - cd flutter_local_notifications_platform_interface
    - flutter test

test_plugin_task:
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  test_script:
    - cd flutter_local_notifications
    - flutter test