task:
  name: Build Android example app
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  install_melos_script:
    - dart pub global activate melos
  build_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run build:example_android

task:
  name: Build iOS example app
  osx_instance:
    image: monterey-xcode
  pub_cache:
    folder: ~/.pub-cache
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  install_melos_script:
    - dart pub global activate melos
  build_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run build:example_ios

task:
  name: Build macOS example app
  osx_instance:
    image: monterey-xcode
  pub_cache:
    folder: ~/.pub-cache
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  setup_script:
    - flutter config --enable-macos-desktop
  install_melos_script:
    - dart pub global activate melos
  build_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run build:example_macos

task:
  name: Build Linux example app
  container:
    image: cirrusci/flutter:stable
  pub_cache:
    folder: ~/.pub-cache
  setup_script:
    - apt update
    - apt install cmake ninja-build clang pkg-config libgtk-3-dev -y
    - flutter config --enable-linux-desktop
  install_melos_script:
    - dart pub global activate melos
  build_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run build:example_linux

task:
  name: Run all unit tests (Dart)
  container:
    image: cirrusci/flutter:stable
  install_melos_script:
    - dart pub global activate melos
  test_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run test:unit --no-select

task:
  name: Run integration tests (Android)
  env:
    EMULATOR_API_LEVEL: 28
    ANDROID_ABI: "default;x86"
  container:
    image: cirrusci/flutter:stable
    cpu: 4
    memory: 10G
    kvm: true
  pub_cache:
    folder: ~/.pub-cache
  install_melos_script:
    - dart pub global activate melos
  install_images_script: sdkmanager "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  create_device_script:
    echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API_LEVEL;$ANDROID_ABI"
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator -no-window -verbose -avd test -no-audio -no-window
  wait_for_emulator_script:
    android-wait-for-emulator
  test_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter precache
    - melos bootstrap
    - melos run build:example_android
    - melos run test:integration
task:
  name: Run integration tests (iOS)
  osx_instance:
    image: monterey-xcode-13.3
  pub_cache:
    folder: ~/.pub-cache
  simulator_script:
    - xcrun simctl list devicetypes
    - xcrun simctl list runtimes
    # create simulator
    - udid=$(xcrun simctl create "iPhone 13" com.apple.CoreSimulator.SimDeviceType.iPhone-13 com.apple.CoreSimulator.SimRuntime.iOS-15-4)
    # boot simulator
    - xcrun simctl boot $udid
    # enable notifications permissions via AppleSimulatorUtils
    - brew tap wix/brew
    - brew install applesimutils
    - applesimutils --byId $udid --bundle com.dexterous.flutterLocalNotificationsExample --setPermissions notifications=YES
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
  install_melos_script:
    - dart pub global activate melos
  test_script:
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - melos bootstrap
    - melos run test:integration