# Generated file - do not commit this file.
description: "Demonstrates how to use the flutter_local_notifications plugin."
name: "flutter_local_notifications_example"
publish_to: "none"
dependencies: 
  cupertino_icons: "^1.0.2"
  device_info: "^2.0.2"
  flutter_native_timezone: "^2.0.0"
  http: "^0.13.4"
  image: "^3.0.8"
  path_provider: "^2.0.0"
  rxdart: "^0.27.2"
  shared_preferences: "^2.0.1"
  url_launcher: "^6.0.17"
  flutter: 
    sdk: "flutter"
  flutter_local_notifications: 
    path: "../"
dependency_overrides: 
  flutter_local_notifications: 
    path: ".."
  flutter_local_notifications_linux: 
    path: "..\\..\\flutter_local_notifications_linux"
  flutter_local_notifications_platform_interface: 
    path: "..\\..\\flutter_local_notifications_platform_interface"
dev_dependencies: 
  msix: "^2.8.17"
  flutter_driver: 
    sdk: "flutter"
  flutter_test: 
    sdk: "flutter"
  integration_test: 
    sdk: "flutter"
environment: 
  flutter: ">=1.26.0-0"
  sdk: ">=2.12.0-0 <3.0.0"
flutter: 
  assets: 
    - "icons/"
    - "sound/"
  uses-material-design: true
msix_config: 
  display_name: "Flutter Local Notifications Example"
  identity_name: "Com.Example.FlutterLocalNotificationsExample"
  debug: true
