# Generated file - do not commit this file.
description: "Linux implementation of the flutter_local_notifications plugin"
homepage: "https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications"
name: "flutter_local_notifications_linux"
version: "0.4.1+1"
dependencies: 
  dbus: "^0.6.0"
  flutter_local_notifications_platform_interface: "^6.0.0"
  path: "^1.8.0"
  xdg_directories: "^0.2.0"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  flutter_local_notifications_platform_interface: 
    path: "..\\flutter_local_notifications_platform_interface"
dev_dependencies: 
  mocktail: "^0.1.4"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=2.2.0"
  sdk: ">=2.12.0 <3.0.0"
