# Generated file - do not commit this file.
description: "A common platform interface for the flutter_local_notifications plugin."
homepage: "https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications_platform_interface"
name: "flutter_local_notifications_platform_interface"
version: "6.0.0"
dependencies: 
  plugin_platform_interface: "^2.0.0"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  mockito: "^5.0.8"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=2.2.0"
  sdk: ">=2.12.0 <3.0.0"
