# Generated file - do not commit this file.
description: "A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform."
homepage: "https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications"
name: "flutter_local_notifications"
version: "9.2.0"
dependencies: 
  clock: "^1.1.0"
  flutter_local_notifications_linux: "^0.4.1"
  flutter_local_notifications_platform_interface: "^6.0.0"
  timezone: "^0.8.0"
  flutter: 
    sdk: "flutter"
dependency_overrides: 
  flutter_local_notifications_linux: 
    path: "..\\flutter_local_notifications_linux"
  flutter_local_notifications_platform_interface: 
    path: "..\\flutter_local_notifications_platform_interface"
dev_dependencies: 
  mockito: "^5.0.8"
  plugin_platform_interface: "^2.0.0"
  flutter_driver: 
    sdk: "flutter"
  flutter_test: 
    sdk: "flutter"
environment: 
  flutter: ">=2.2.0"
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  plugin: 
    platforms: 
      android: 
        package: "com.dexterous.flutterlocalnotifications"
        pluginClass: "FlutterLocalNotificationsPlugin"
      ios: 
        pluginClass: "FlutterLocalNotificationsPlugin"
      linux: 
        default_package: "flutter_local_notifications_linux"
      macos: 
        pluginClass: "FlutterLocalNotificationsPlugin"
      windows: 
        pluginClass: "FlutterLocalNotificationsPlugin"
