name: flutter_local_notifications_web
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/cylyl/flutter_local_notifications

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications_platform_interface:
#    path: ../flutter_local_notifications_platform_interface
    git:
      url: https://github.com/cylyl/flutter_local_notifications
      path: flutter_local_notifications_platform_interface
  flutter_web_plugins:
    sdk: flutter
  timezone: ^0.8.0
  firebase_core:
  firebase_messaging:
  firebase_core_web:
  firebase_messaging_web:
  import_js_library:
    git:
      url: https://github.com/cylyl/flutter_web_import_js_library.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterLocalNotificationsWeb
        fileName: flutter_local_notifications_web.dart

  assets:
    - assets/flutter_local_notifications_web.js